name: Deploy App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Backend
      run: |
        docker build -t my-backend ./backend
        docker tag my-backend my-dockerhub-user/my-backend:latest
        docker push my-dockerhub-user/my-backend:latest

    - name: Build and Push Frontend
      run: |
        docker build -t my-frontend ./frontend
        docker tag my-frontend my-dockerhub-user/my-frontend:latest
        docker push my-dockerhub-user/my-frontend:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy with Helm
      run: |
        helm upgrade --install myapp ./helm/myapp           --set backend.image=my-dockerhub-user/my-backend:latest           --set frontend.image=my-dockerhub-user/my-frontend:latest
